### ISSUE TITLE
Release based on recent changes?

### ISSUE THREAD

**Issue by grodin** [Naturally-Being/G-Rex#12]
Just wondering if there's any chance of a release happening soon based on what we merged? If there's work that needs doing to get it ready I'm happy to help.

**Comment by chris-horner** [comment]
Sorry I haven't gotten around to this. Works has been in super crunch mode at the moment gearing up for a release. I'll aim to push this out later today or early tomorrow.

**Comment by grodin** [comment]
Not a problem. It was intended as a small reminder, rather than a demand.

Like I said, I'm happy to help with any work that needs doing, just not
sure what your release process is for this. Might be worth documenting it
once you've got some time again, but paying work obviously comes first.

**Comment by chris-horner** [comment]
3.0.0 has been pushed to Central! Thanks again for all your awesome work on this, and for reminding me to actually push a release.
